name: Use Action

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  use-action:
    name: Use Action
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - uses: actions/checkout@v4

      - uses: ./
      - run: |
          crane digest ubuntu
          crane manifest ubuntu | jq
          crane copy ubuntu ghcr.io/${{ github.repository }}/ubuntu-copy

      - name: Install old release
        uses: ./
        with:
          version: v0.12.0
      - name: Check installed version
        run: crane version | grep 0.12.0

      - name: Install from tip
        uses: ./
        with:
          version: tip
      - name: Check installed version (tip)
        run: |
          rm $(which crane) # Uninstall previous versions.
          crane version
